name: Test Workflow

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Print a message
      run: echo "Hello, world!"
