
name: Deploy Gatsby Sites

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies and build
      run: |
        npm ci
        gatsby build

    - name: Deploy to DigitalOcean
      env:
        DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
        DO_USER: ${{ secrets.DO_USER }}
        DO_HOST: ${{ secrets.DO_HOST }}
        DO_PATH: ${{ secrets.DO_PATH }}
      run: |
         sudo apt-get install -y sshpass
         sshpass -p "$DO_PASSWORD" rsync -avP --delete -e "ssh" ./public/ $DO_USER@$DO_HOST:$DO_PATH

